[package]
name = "day20"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
itertools = "0.13.0"
regex = "1.11.1"
fxhash = "0.2.1"
num-complex = "0.4.6"


